# Harmony Jekyll theme general configurations

url: https://gangoffork.github.io

harmony:
  name: Gang of Fork
  description: Gang of Fork, bitch!
  meta_description: We are the Gang of Fork!
  basetheme: theme-base-01
  authors:
    bruno:
      name: Bruno Lima
    chico:
      name: Francisco Marinho
    deni:
      name: Deni Cavalcanti
    edson:
      name: Edson Samuel Jr

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-66157363-1

  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings
markdown:    kramdown
highlighter: pygments

# Permalinks
permalink: /:categories/:year/:title.html

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
